<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE students SYSTEM "D:\代码\idea java\test\Learn\Html_Demo\XML_Demo\dtd\student.dtd">
<!--<!DOCTYPE students[
        <!ELEMENT students (student+) >
        <!ELEMENT student (name,age,sex) >
        <!ELEMENT name (#PCDATA) >
        <!ELEMENT age (#PCDATA) >
        <!ELEMENT sex (#PCDATA) >
        <!ATTLIST student number ID #REQUIRED>
        ]>-->
<students>
    <student number="s001">
        <name>张三</name>
        <age>24</age>
        <sex>男</sex>
    </student>
    
    <student number="s002">
        <name>李四</name>
        <age>26</age>
        <sex>女</sex>
    </student>
</students>